doc-warnings: no
test-warnings: no
strictness: medium
max-line-length: 120
uses:
    - django
autodetect: yes
requirements:
    - OIPA/requirements.txt
ignore-paths:
    - bin
    - docs
    - etc
    - fixtures
    - OIPA/static
python-targets:
    - 2
