language: python
python:
  - "2.7"

# setup database
before_install:
  - mysql -e 'create database oipa_test COLLATE utf8_unicode_ci;'


# command to install dependencies
install: 
  - "pip install -r OIPA/requirements.txt"
  - "pip install -r OIPA/test_requirements.txt"
  - "echo -e 'no\n' | OIPA/manage.py syncdb --settings=OIPA.test_settings"

# create full text search indexes after running syncdb (disabled for now because of problems with mysql version
#before_script:
#  - mysql oipa_test < OIPA/create_fts_indexes.sql

# command to run tests
script: cd OIPA/ && py.test --ds=OIPA.test_settings && cd ..
