dist: trusty
sudo: required
language: shell

services:
  - docker


before_install:
  - make build

script:
  - make migrate
  - make test-coverage

after_success:
  - make coveralls
after_failure:
  - make coveralls
