# Docker Compose file for OIPA development
#
#

version: "2"
services:

  postgres:
    image: mdillon/postgis:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=oipa
      - POSTGRES_USER=oipa
      - POSTGRES_PASSWORD=oipa
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"

  oipa:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - etc/env.docker
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  oipa-supervisor:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py supervisor
    env_file:
      - etc/env.docker
    volumes:
      - .:/app/src
    depends_on:
      - postgres
      - redis